#!/usr/bin/env bash
# Cloudflare Pages build: writes assets/config.js from the project's
# environment variables. Build command: `bash web/build.sh`, output: `web`.
#
#   SUPABASE_URL        https://<project>.supabase.co
#   SUPABASE_ANON_KEY   the anon (public) key
#   APP_STORE_URL       App Store or TestFlight public link
#   ANDROID_URL         optional
#   SUPPORT_EMAIL       where support mail goes
#   APPLE_TEAM_ID       for universal links (default: the app's team)
set -euo pipefail
cd "$(dirname "$0")"
json() { python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$1"; }
cat > assets/config.js <<JS
// Generated by web/build.sh — do not edit.
window.PICKLEBALL = {
  supabaseUrl: $(json "${SUPABASE_URL:-}"),
  supabaseAnonKey: $(json "${SUPABASE_ANON_KEY:-}"),
  appStoreUrl: $(json "${APP_STORE_URL:-https://apps.apple.com/}"),
  androidUrl: $(json "${ANDROID_URL:-}"),
  supportEmail: $(json "${SUPPORT_EMAIL:-support@example.com}")
};
JS
echo "wrote web/assets/config.js"

# Universal links: invite links open the app directly when it's installed.
mkdir -p .well-known
cat > .well-known/apple-app-site-association <<JSON
{
  "applinks": {
    "details": [
      {
        "appIDs": ["${APPLE_TEAM_ID:-3A8H924A89}.ME.PickleBall"],
        "components": [
          { "/": "/invite/*", "comment": "friend, squad and claim links" },
          { "/": "/invite", "?": { "t": "*" } },
          { "/": "/invite/", "?": { "t": "*" } }
        ]
      }
    ]
  }
}
JSON
echo "wrote web/.well-known/apple-app-site-association"

